// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: decompositionpb/decomposition.proto

package decompositionpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Decomposition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *Decomposition) Reset() {
	*x = Decomposition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_decompositionpb_decomposition_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Decomposition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decomposition) ProtoMessage() {}

func (x *Decomposition) ProtoReflect() protoreflect.Message {
	mi := &file_decompositionpb_decomposition_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decomposition.ProtoReflect.Descriptor instead.
func (*Decomposition) Descriptor() ([]byte, []int) {
	return file_decompositionpb_decomposition_proto_rawDescGZIP(), []int{0}
}

func (x *Decomposition) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type DecompositionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Decomposition *Decomposition `protobuf:"bytes,1,opt,name=decomposition,proto3" json:"decomposition,omitempty"`
}

func (x *DecompositionRequest) Reset() {
	*x = DecompositionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_decompositionpb_decomposition_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecompositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecompositionRequest) ProtoMessage() {}

func (x *DecompositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_decompositionpb_decomposition_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecompositionRequest.ProtoReflect.Descriptor instead.
func (*DecompositionRequest) Descriptor() ([]byte, []int) {
	return file_decompositionpb_decomposition_proto_rawDescGZIP(), []int{1}
}

func (x *DecompositionRequest) GetDecomposition() *Decomposition {
	if x != nil {
		return x.Decomposition
	}
	return nil
}

type DecompositionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DecompositionResponse) Reset() {
	*x = DecompositionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_decompositionpb_decomposition_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecompositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecompositionResponse) ProtoMessage() {}

func (x *DecompositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_decompositionpb_decomposition_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecompositionResponse.ProtoReflect.Descriptor instead.
func (*DecompositionResponse) Descriptor() ([]byte, []int) {
	return file_decompositionpb_decomposition_proto_rawDescGZIP(), []int{2}
}

func (x *DecompositionResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_decompositionpb_decomposition_proto protoreflect.FileDescriptor

var file_decompositionpb_decomposition_proto_rawDesc = []byte{
	0x0a, 0x23, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x70,
	0x62, 0x2f, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x6f, 0x6e, 0x22, 0x27, 0x0a, 0x0d, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x59, 0x0a, 0x14,
	0x44, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x41, 0x0a, 0x0d, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x64, 0x65,
	0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x6e, 0x2e, 0x44, 0x65, 0x63, 0x6f, 0x6d,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2f, 0x0a, 0x15, 0x44, 0x65, 0x63, 0x6f, 0x6d,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x72, 0x0a, 0x14, 0x44, 0x65, 0x63, 0x6f,
	0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x5a, 0x0a, 0x0d, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x22, 0x2e, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x6e,
	0x2e, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x6f, 0x6e, 0x2e, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x13, 0x5a, 0x11,
	0x2e, 0x2f, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_decompositionpb_decomposition_proto_rawDescOnce sync.Once
	file_decompositionpb_decomposition_proto_rawDescData = file_decompositionpb_decomposition_proto_rawDesc
)

func file_decompositionpb_decomposition_proto_rawDescGZIP() []byte {
	file_decompositionpb_decomposition_proto_rawDescOnce.Do(func() {
		file_decompositionpb_decomposition_proto_rawDescData = protoimpl.X.CompressGZIP(file_decompositionpb_decomposition_proto_rawDescData)
	})
	return file_decompositionpb_decomposition_proto_rawDescData
}

var file_decompositionpb_decomposition_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_decompositionpb_decomposition_proto_goTypes = []interface{}{
	(*Decomposition)(nil),         // 0: decompositon.Decomposition
	(*DecompositionRequest)(nil),  // 1: decompositon.DecompositionRequest
	(*DecompositionResponse)(nil), // 2: decompositon.DecompositionResponse
}
var file_decompositionpb_decomposition_proto_depIdxs = []int32{
	0, // 0: decompositon.DecompositionRequest.decomposition:type_name -> decompositon.Decomposition
	1, // 1: decompositon.DecompositionService.Decomposition:input_type -> decompositon.DecompositionRequest
	2, // 2: decompositon.DecompositionService.Decomposition:output_type -> decompositon.DecompositionResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_decompositionpb_decomposition_proto_init() }
func file_decompositionpb_decomposition_proto_init() {
	if File_decompositionpb_decomposition_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_decompositionpb_decomposition_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Decomposition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_decompositionpb_decomposition_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecompositionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_decompositionpb_decomposition_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecompositionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_decompositionpb_decomposition_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_decompositionpb_decomposition_proto_goTypes,
		DependencyIndexes: file_decompositionpb_decomposition_proto_depIdxs,
		MessageInfos:      file_decompositionpb_decomposition_proto_msgTypes,
	}.Build()
	File_decompositionpb_decomposition_proto = out.File
	file_decompositionpb_decomposition_proto_rawDesc = nil
	file_decompositionpb_decomposition_proto_goTypes = nil
	file_decompositionpb_decomposition_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DecompositionServiceClient is the client API for DecompositionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DecompositionServiceClient interface {
	//server streaming
	Decomposition(ctx context.Context, in *DecompositionRequest, opts ...grpc.CallOption) (DecompositionService_DecompositionClient, error)
}

type decompositionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDecompositionServiceClient(cc grpc.ClientConnInterface) DecompositionServiceClient {
	return &decompositionServiceClient{cc}
}

func (c *decompositionServiceClient) Decomposition(ctx context.Context, in *DecompositionRequest, opts ...grpc.CallOption) (DecompositionService_DecompositionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DecompositionService_serviceDesc.Streams[0], "/decompositon.DecompositionService/Decomposition", opts...)
	if err != nil {
		return nil, err
	}
	x := &decompositionServiceDecompositionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DecompositionService_DecompositionClient interface {
	Recv() (*DecompositionResponse, error)
	grpc.ClientStream
}

type decompositionServiceDecompositionClient struct {
	grpc.ClientStream
}

func (x *decompositionServiceDecompositionClient) Recv() (*DecompositionResponse, error) {
	m := new(DecompositionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DecompositionServiceServer is the server API for DecompositionService service.
type DecompositionServiceServer interface {
	//server streaming
	Decomposition(*DecompositionRequest, DecompositionService_DecompositionServer) error
}

// UnimplementedDecompositionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDecompositionServiceServer struct {
}

func (*UnimplementedDecompositionServiceServer) Decomposition(*DecompositionRequest, DecompositionService_DecompositionServer) error {
	return status.Errorf(codes.Unimplemented, "method Decomposition not implemented")
}

func RegisterDecompositionServiceServer(s *grpc.Server, srv DecompositionServiceServer) {
	s.RegisterService(&_DecompositionService_serviceDesc, srv)
}

func _DecompositionService_Decomposition_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DecompositionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DecompositionServiceServer).Decomposition(m, &decompositionServiceDecompositionServer{stream})
}

type DecompositionService_DecompositionServer interface {
	Send(*DecompositionResponse) error
	grpc.ServerStream
}

type decompositionServiceDecompositionServer struct {
	grpc.ServerStream
}

func (x *decompositionServiceDecompositionServer) Send(m *DecompositionResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _DecompositionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "decompositon.DecompositionService",
	HandlerType: (*DecompositionServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Decomposition",
			Handler:       _DecompositionService_Decomposition_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "decompositionpb/decomposition.proto",
}
